"use client";

import React, { useState } from "react";
import { ArrowLeft, Copy, Check } from "lucide-react";
import Image from "next/image";
import QRcode from "@/public/BarCode.svg";

interface EnableTwoFactorModalProps {
  onClose: () => void;
  onSuccess: () => void;
}

export default function EnableTwoFactorModal({
  onClose,
  onSuccess,
}: EnableTwoFactorModalProps) {
  const [code, setCode] = useState(["", "", "", "", "", ""]);
  const [copied, setCopied] = useState(false);
  const manualKey = "123456789098";

  const handleInputChange = (index: number, value: string) => {
    if (value.length > 1) return;
    if (!/^\d*$/.test(value)) return;

    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);

    // Auto-focus next input
    if (value && index < 5) {
      const nextInput = document.getElementById(`code-input-${index + 1}`);
      nextInput?.focus();
    }

    // Check if all inputs are filled
    if (
      newCode.every((digit) => digit !== "") &&
      newCode.join("").length === 6
    ) {
      // Simulate validation delay
      setTimeout(() => {
        onSuccess();
      }, 500);
    }
  };

  const handleKeyDown = (
    index: number,
    e: React.KeyboardEvent<HTMLInputElement>,
  ) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      const prevInput = document.getElementById(`code-input-${index - 1}`);
      prevInput?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData("text").slice(0, 6);
    if (/^\d+$/.test(pastedData)) {
      const newCode = pastedData
        .split("")
        .concat(Array(6 - pastedData.length).fill(""));
      setCode(newCode.slice(0, 6));
      const nextEmptyIndex = Math.min(pastedData.length, 5);
      const nextInput = document.getElementById(`code-input-${nextEmptyIndex}`);
      nextInput?.focus();
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(manualKey);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in"
      onClick={onClose}
    >
      <div
        className="  relative  shadow-2xl animate-scale-up"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="overflow-y-scroll w-full md:w-[812px]   overflow-hidden bg-[#161E22] border border-[#1C252A]  rounded-3xl max-h-[90vh]  no-scrollbar">
          {/* Header */}
          <div className="flex rounded-3xl bg-[#161E22] absolute top-0 left-0 right-0 z-10 bg-gray-700s items-center gap-4 p-6 border-b border-[#1C252A]">
            <button
              onClick={onClose}
              className="text-[#92A5A8] hover:text-[#FCFFFF] transition-colors"
            >
              <ArrowLeft size={20} />
            </button>
            <h2 className="text-[14px]  font-extralight text-[#92A5A8] uppercase tracking-wide">
              Enable Two-Factor Authentication
            </h2>
          </div>

          {/* Content */}
          <div className="p-6 space-y-6 mt-14">
            <div>
              <h3 className="text-xl text-center font-semibold text-[#FCFFFF] mb-2">
                Enable 2FA on InheritX
              </h3>
              <p className="text-[12px] text-center font-extralight text-[#92A5A8]">
                Scan this QR code with your authenticator app (Google
                Authenticator, Authy, etc.) or copy the manual key
              </p>
            </div>

            {/* QR Code */}
            <div className="flex justify-center">
              <div className="bg-transparent  rounded-lg border border-black">
                <div className="w-48 h-48 bg-transparent rounded flex items-center justify-center">
                  {/* QR Code Pattern - Replace with actual QR code generation library */}
                  <div className="w-full h-full bg-transparent rounded">
                    <Image
                      src={QRcode}
                      className="h-full w-full"
                      alt="QR Code"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Manual Key */}
            <div>
              <p className="text-sm text-center font-extralight text-[#92A5A8] mb-2">
                Manual Key:{" "}
                <span className="text-white mx-3 text-[16px] font-bold">
                  {manualKey}
                </span>
              </p>
            </div>

            {/* Code Input */}
            <div>
              <p className="text-sm text-center text-[#92A5A8] mb-4">
                Enter the 6-digit code generated by your authenticator app
              </p>
              <div className="flex gap-2 justify-center">
                {code.map((digit, index) => (
                  <input
                    key={index}
                    id={`code-input-${index}`}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleInputChange(index, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(index, e)}
                    onPaste={handlePaste}
                    className="w-12 h-14 text-center text-xl font-semibold bg-[#1C252A] border border-[#2A3338] rounded-lg text-[#FCFFFF] focus:outline-none focus:ring-2 focus:ring-[#33C5E0] focus:border-transparent"
                  />
                ))}
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="flex flex-col-reverse md:flex-row gap-3 p-6 border-t border-[#1C252A]">
            <button
              onClick={onClose}
              className="flex-1 py-3 px-4 bg-[#1C252A] text-[#FCFFFF] rounded-full hover:bg-[#2A3338] transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={() => {
                if (code.every((d) => d !== "") && code.join("").length === 6) {
                  onSuccess();
                }
              }}
              disabled={
                code.some((d) => d === "") || code.join("").length !== 6
              }
              className="flex-1 py-3 px-4 bg-[#33C5E0] text-[#2A3338] rounded-full  transition-colors  disabled:cursor-not-allowed"
            >
              Continue
            </button>
          </div>
        </div>

        
      </div>
    </div>
  );
}
